"""update habit model

Revision ID: 33c690c05bfb
Revises: 1
Create Date: 2025-04-24 11:34:56.917248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33c690c05bfb'
down_revision = '1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('category', sa.String(), nullable=True))
    op.add_column('habits', sa.Column('color', sa.String(), nullable=True))
    op.add_column('habits', sa.Column('completed', sa.Boolean(), nullable=True))
    op.alter_column('habits', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('habits', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('habits', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_habits_id'), 'habits', ['id'], unique=False)
    op.create_index(op.f('ix_habits_title'), 'habits', ['title'], unique=False)
    op.drop_column('habits', 'frequency')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('habits', sa.Column('frequency', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_habits_title'), table_name='habits')
    op.drop_index(op.f('ix_habits_id'), table_name='habits')
    op.alter_column('habits', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('habits', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('habits', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('habits', 'completed')
    op.drop_column('habits', 'color')
    op.drop_column('habits', 'category')
    # ### end Alembic commands ### 