"""Remove completed field from Habit

Revision ID: 575bd4a0592f
Revises: db5e185308f3
Create Date: 2025-04-24 13:22:23.509965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575bd4a0592f'
down_revision = 'db5e185308f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ### 