"""enable cascade delete for habit logs

Revision ID: d86d92c09d3b
Revises: 575bd4a0592f
Create Date: 2025-04-24 13:33:23.223671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86d92c09d3b'
down_revision = '575bd4a0592f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('habit_logs_habit_id_fkey', 'habit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'habit_logs', 'habits', ['habit_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habit_logs', type_='foreignkey')
    op.create_foreign_key('habit_logs_habit_id_fkey', 'habit_logs', 'habits', ['habit_id'], ['id'])
    # ### end Alembic commands ### 